function libTemplate() {
  return 'libTemplate'
}

export default libTemplate

export * from './core/func1'
export * from './core/func2'

// --- Auto-Generated By Unplugin-Export-Collector ---

const __UnExportList = ["func1","func2"] as const

export function autoImport(map?: Partial<{ [K in typeof __UnExportList[number]]: string }>): Record<string, (string | [string, string])[]> {
  return {
    'lib-template': __UnExportList.map(v => map && map[v] ? [v, map[v]] as [string, string] : v),
  }
}

// --- Auto-Generated By Unplugin-Export-Collector ---
