function libTemplate() {
  return 'libTemplate'
}

export default libTemplate

export * from './core/func1'
export * from './core/func2'

// --- Auto-Generated By Export-Collector ---

const exportList = ["func1","func2"] as const

export type AutoImportMap = { [K in typeof exportList[number]]: string }
export function autoImport(map?: Partial<AutoImportMap>): Record<string, (string | [string, string])[]> {
  return {
    'lib-template': exportList.map(v => map && map[v] ? [v, map[v]] as [string, string] : v),
  }
}

// --- Auto-Generated By Export-Collector ---
